#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "task_app"
name = "Task App"
description.en = "Cross-project task and team management with Kanban, Gantt and calendar views"
description.fr = "Gestion de tâches et d'équipes multi-projets avec vues Kanban, Gantt et calendrier"

version = "0.1.4~ynh1"

maintainers = ["studion79"]

[upstream]
license = "AGPL-3.0-only"
code = "https://github.com/studion79/studion-tasks"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "500M"
ram.build = "512M"
ram.runtime = "150M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
    [resources.sources.main]
    url = "https://github.com/studion79/studion-tasks/archive/refs/tags/v0.1.4.tar.gz"
    sha256 = "e38f5c605ec49382a2c2a26d0cb40d719d7ad508d2b963b4047ca681dd428074"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "nodejs"

    [resources.apt.extras.nodesource]
    repo = "deb https://deb.nodesource.com/node_20.x nodistro main"
    key = "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key"
    packages = "nodejs"
