#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"
chown -R "$app:$app" "$data_dir"
chmod -R 750 "$data_dir"

# Re-create uploads symlink in case it wasn't in the backup
if [ ! -L "$install_dir/public/uploads" ]; then
    rm -rf "$install_dir/public/uploads"
    ln -s "$data_dir/uploads" "$install_dir/public/uploads"
    chown -h "$app:www-data" "$install_dir/public/uploads"
fi

#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet
yunohost service add "$app" --description="Task App service" --log="/var/log/$app/$app.log"
ynh_restore "/etc/logrotate.d/$app"

#=================================================
ynh_script_progression "Reloading NGINX and starting $app's service..."

ynh_systemctl --service="$app" --action="start"
ynh_systemctl --service=nginx --action=reload

#=================================================
ynh_script_progression "Restoration completed for $app"
